// 비디오: 영상, 챕터, 자막, 시청기록, 라이브, 댓글, 재생목록

import { sqliteTable, text, integer, uniqueIndex, index, type AnySQLiteColumn } from 'drizzle-orm/sqlite-core';
import { sql } from 'drizzle-orm';

import { tenants } from './tenant';

import { courses } from './content';

// ============================================================
// Epic 23: Video Streaming & Live Features
// ============================================================

// Videos Table (비디오 콘텐츠)
export const videos = sqliteTable('videos', {
  id: integer('id').primaryKey({ autoIncrement: true }),
  tenantId: integer('tenant_id').default(1).references(() => tenants.id), // SaaS 멀티테넌시
  title: text('title').notNull(),
  description: text('description'),
  courseId: integer('course_id').references(() => courses.id, { onDelete: 'cascade' }),
  originalFileName: text('original_file_name'),
  fileSize: integer('file_size'), // bytes
  duration: integer('duration').notNull(), // 초 단위
  thumbnailUrl: text('thumbnail_url'),
  status: text('status', { enum: ['uploading', 'processing', 'ready', 'failed', 'archived'] }).default('uploading').notNull(),
  processingProgress: integer('processing_progress').default(0), // 0-100
  // Streaming URLs
  hlsUrl: text('hls_url'), // HLS master playlist URL
  dashUrl: text('dash_url'), // DASH manifest URL
  mp4Url: text('mp4_url'), // Direct MP4 URL (fallback)
  // Resolutions
  resolutions: text('resolutions'), // JSON array: ["360p", "720p", "1080p"]
  // DRM
  drmEnabled: integer('drm_enabled', { mode: 'boolean' }).default(false),
  drmProvider: text('drm_provider'), // 'widevine', 'fairplay', 'playready'
  // Analytics
  viewCount: integer('view_count').default(0).notNull(),
  likeCount: integer('like_count').default(0).notNull(),
  commentCount: integer('comment_count').default(0).notNull(),
  averageWatchTime: integer('average_watch_time'), // 초 단위
  completionRate: integer('completion_rate'), // 0-100
  // Access Control
  visibility: text('visibility', { enum: ['public', 'unlisted', 'private', 'members_only'] }).default('public').notNull(),
  allowDownload: integer('allow_download', { mode: 'boolean' }).default(false),
  // Metadata
  tags: text('tags'), // JSON array
  category: text('category'),
  language: text('language').default('ko'),
  uploadedBy: text('uploaded_by').notNull(),
  createdAt: integer('created_at', { mode: 'timestamp' }).default(sql`CURRENT_TIMESTAMP`).notNull(),
  updatedAt: integer('updated_at', { mode: 'timestamp' }).default(sql`CURRENT_TIMESTAMP`).notNull()
}, (table) => [
  index('idx_videos_tenant').on(table.tenantId),
]);

// Video Chapters Table (비디오 챕터)
export const videoChapters = sqliteTable('video_chapters', {
  id: integer('id').primaryKey({ autoIncrement: true }),
  tenantId: integer('tenant_id').default(1).references(() => tenants.id), // SaaS 멀티테넌시
  videoId: integer('video_id').notNull().references(() => videos.id, { onDelete: 'cascade' }),
  title: text('title').notNull(),
  startTime: integer('start_time').notNull(), // 초 단위
  endTime: integer('end_time').notNull(),
  thumbnailUrl: text('thumbnail_url'),
  order: integer('order').notNull(),
  createdAt: integer('created_at', { mode: 'timestamp' }).default(sql`CURRENT_TIMESTAMP`).notNull()
}, (table) => [
  index('idx_video_chapters_tenant').on(table.tenantId),
]);

// Video Subtitles Table (자막)
export const videoSubtitles = sqliteTable('video_subtitles', {
  id: integer('id').primaryKey({ autoIncrement: true }),
  tenantId: integer('tenant_id').default(1).references(() => tenants.id), // SaaS 멀티테넌시
  videoId: integer('video_id').notNull().references(() => videos.id, { onDelete: 'cascade' }),
  language: text('language').notNull(), // 'ko', 'en', 'ja'
  label: text('label').notNull(), // '한국어', 'English', '日本語'
  format: text('format', { enum: ['srt', 'vtt', 'ass'] }).default('vtt').notNull(),
  fileUrl: text('file_url').notNull(),
  isDefault: integer('is_default', { mode: 'boolean' }).default(false),
  isAutoGenerated: integer('is_auto_generated', { mode: 'boolean' }).default(false),
  createdAt: integer('created_at', { mode: 'timestamp' }).default(sql`CURRENT_TIMESTAMP`).notNull()
}, (table) => [
  index('idx_video_subtitles_tenant').on(table.tenantId),
]);

// Watch History Table (시청 기록)
export const watchHistory = sqliteTable('watch_history', {
  id: integer('id').primaryKey({ autoIncrement: true }),
  tenantId: integer('tenant_id').default(1).references(() => tenants.id), // SaaS 멀티테넌시
  userId: text('user_id').notNull(),
  userType: text('user_type', { enum: ['distributor', 'pd', 'customer'] }).notNull(),
  videoId: integer('video_id').notNull().references(() => videos.id, { onDelete: 'cascade' }),
  watchedDuration: integer('watched_duration').notNull(), // 초 단위
  lastPosition: integer('last_position').notNull(), // 마지막 재생 위치 (초)
  completed: integer('completed', { mode: 'boolean' }).default(false),
  completedAt: integer('completed_at', { mode: 'timestamp' }),
  device: text('device'), // 'desktop', 'mobile', 'tablet'
  quality: text('quality'), // '360p', '720p', '1080p'
  lastWatchedAt: integer('last_watched_at', { mode: 'timestamp' }).default(sql`CURRENT_TIMESTAMP`).notNull(),
  createdAt: integer('created_at', { mode: 'timestamp' }).default(sql`CURRENT_TIMESTAMP`).notNull()
}, (table) => [
  index('idx_watch_history_tenant').on(table.tenantId),
]);

// Live Streams Table (라이브 스트리밍)
export const liveStreams = sqliteTable('live_streams', {
  id: integer('id').primaryKey({ autoIncrement: true }),
  tenantId: integer('tenant_id').default(1).references(() => tenants.id), // SaaS 멀티테넌시
  title: text('title').notNull(),
  description: text('description'),
  scheduledStartTime: integer('scheduled_start_time', { mode: 'timestamp' }).notNull(),
  scheduledEndTime: integer('scheduled_end_time', { mode: 'timestamp' }),
  actualStartTime: integer('actual_start_time', { mode: 'timestamp' }),
  actualEndTime: integer('actual_end_time', { mode: 'timestamp' }),
  status: text('status', { enum: ['scheduled', 'live', 'ended', 'cancelled'] }).default('scheduled').notNull(),
  // Streaming
  streamKey: text('stream_key').notNull(),
  rtmpUrl: text('rtmp_url').notNull(),
  hlsPlaybackUrl: text('hls_playback_url'),
  // Settings
  maxViewers: integer('max_viewers').default(1000),
  currentViewers: integer('current_viewers').default(0),
  peakViewers: integer('peak_viewers').default(0),
  totalViews: integer('total_views').default(0),
  enableChat: integer('enable_chat', { mode: 'boolean' }).default(true),
  enableRecording: integer('enable_recording', { mode: 'boolean' }).default(true),
  recordingUrl: text('recording_url'), // VOD URL after stream ends
  // Metadata
  thumbnailUrl: text('thumbnail_url'),
  tags: text('tags'), // JSON array
  category: text('category'),
  visibility: text('visibility', { enum: ['public', 'unlisted', 'private'] }).default('public').notNull(),
  hostedBy: text('hosted_by').notNull(),
  createdAt: integer('created_at', { mode: 'timestamp' }).default(sql`CURRENT_TIMESTAMP`).notNull(),
  updatedAt: integer('updated_at', { mode: 'timestamp' }).default(sql`CURRENT_TIMESTAMP`).notNull()
}, (table) => [
  index('idx_live_streams_tenant').on(table.tenantId),
]);

// Video Comments Table (비디오 댓글)
export const videoComments = sqliteTable('video_comments', {
  id: integer('id').primaryKey({ autoIncrement: true }),
  tenantId: integer('tenant_id').default(1).references(() => tenants.id), // SaaS 멀티테넌시
  videoId: integer('video_id').notNull().references(() => videos.id, { onDelete: 'cascade' }),
  userId: text('user_id').notNull(),
  userName: text('user_name').notNull(),
  comment: text('comment').notNull(),
  timestamp: integer('timestamp'), // 댓글이 달린 비디오 시간 (초)
  parentCommentId: integer('parent_comment_id').references((): AnySQLiteColumn => videoComments.id, { onDelete: 'cascade' }),
  likeCount: integer('like_count').default(0).notNull(),
  isEdited: integer('is_edited', { mode: 'boolean' }).default(false),
  isPinned: integer('is_pinned', { mode: 'boolean' }).default(false),
  createdAt: integer('created_at', { mode: 'timestamp' }).default(sql`CURRENT_TIMESTAMP`).notNull(),
  updatedAt: integer('updated_at', { mode: 'timestamp' }).default(sql`CURRENT_TIMESTAMP`).notNull()
}, (table) => [
  index('idx_video_comments_tenant').on(table.tenantId),
]);

// Video Playlists Table (재생목록)
export const videoPlaylists = sqliteTable('video_playlists', {
  id: integer('id').primaryKey({ autoIncrement: true }),
  tenantId: integer('tenant_id').default(1).references(() => tenants.id), // SaaS 멀티테넌시
  name: text('name').notNull(),
  description: text('description'),
  thumbnailUrl: text('thumbnail_url'),
  visibility: text('visibility', { enum: ['public', 'unlisted', 'private'] }).default('public').notNull(),
  createdBy: text('created_by').notNull(),
  videoCount: integer('video_count').default(0).notNull(),
  totalDuration: integer('total_duration').default(0), // 초 단위
  createdAt: integer('created_at', { mode: 'timestamp' }).default(sql`CURRENT_TIMESTAMP`).notNull(),
  updatedAt: integer('updated_at', { mode: 'timestamp' }).default(sql`CURRENT_TIMESTAMP`).notNull()
}, (table) => [
  index('idx_video_playlists_tenant').on(table.tenantId),
]);

// Playlist Videos Table (재생목록 비디오 매핑)
export const playlistVideos = sqliteTable('playlist_videos', {
  id: integer('id').primaryKey({ autoIncrement: true }),
  tenantId: integer('tenant_id').default(1).references(() => tenants.id), // SaaS 멀티테넌시
  playlistId: integer('playlist_id').notNull().references(() => videoPlaylists.id, { onDelete: 'cascade' }),
  videoId: integer('video_id').notNull().references(() => videos.id, { onDelete: 'cascade' }),
  order: integer('order').notNull(),
  addedAt: integer('added_at', { mode: 'timestamp' }).default(sql`CURRENT_TIMESTAMP`).notNull()
}, (table) => [
  index('idx_playlist_videos_tenant').on(table.tenantId),
]);

// Export types for Epic 23
export type Video = typeof videos.$inferSelect;
export type NewVideo = typeof videos.$inferInsert;

export type VideoChapter = typeof videoChapters.$inferSelect;
export type NewVideoChapter = typeof videoChapters.$inferInsert;

export type VideoSubtitle = typeof videoSubtitles.$inferSelect;
export type NewVideoSubtitle = typeof videoSubtitles.$inferInsert;

export type WatchHistory = typeof watchHistory.$inferSelect;
export type NewWatchHistory = typeof watchHistory.$inferInsert;

export type LiveStream = typeof liveStreams.$inferSelect;
export type NewLiveStream = typeof liveStreams.$inferInsert;

export type VideoComment = typeof videoComments.$inferSelect;
export type NewVideoComment = typeof videoComments.$inferInsert;

export type VideoPlaylist = typeof videoPlaylists.$inferSelect;
export type NewVideoPlaylist = typeof videoPlaylists.$inferInsert;

export type PlaylistVideo = typeof playlistVideos.$inferSelect;
export type NewPlaylistVideo = typeof playlistVideos.$inferInsert;
