import { NextRequest, NextResponse } from 'next/server';
import { db } from '@/lib/db';
import { videoSubtitles } from '@/lib/db/schema';
import { eq } from 'drizzle-orm';
import { addVideoSubtitle } from '@/lib/video';

/**
 * GET /api/videos/[id]/subtitles
 * Get all subtitles for a video
 */
export async function GET(
  request: NextRequest,
  { params }: { params: { id: string } }
) {
  try {
    const videoId = parseInt(params.id);

    const subtitles = await db
      .select()
      .from(videoSubtitles)
      .where(eq(videoSubtitles.videoId, videoId));

    return NextResponse.json({
      success: true,
      subtitles
    });
  } catch (error) {
    console.error('Error fetching subtitles:', error);
    return NextResponse.json(
      { success: false, error: 'Failed to fetch subtitles' },
      { status: 500 }
    );
  }
}

/**
 * POST /api/videos/[id]/subtitles
 * Add a subtitle to a video
 */
export async function POST(
  request: NextRequest,
  { params }: { params: { id: string } }
) {
  try {
    const videoId = parseInt(params.id);
    const body = await request.json();
    const {
      language,
      label,
      format = 'vtt',
      fileUrl,
      isDefault = false,
      isAutoGenerated = false
    } = body;

    // Validation
    if (!language || !label || !fileUrl) {
      return NextResponse.json(
        { success: false, error: 'Missing required fields' },
        { status: 400 }
      );
    }

    const subtitle = await addVideoSubtitle({
      videoId,
      language,
      label,
      format,
      fileUrl,
      isDefault,
      isAutoGenerated
    });

    return NextResponse.json({
      success: true,
      subtitle
    }, { status: 201 });
  } catch (error) {
    console.error('Error adding subtitle:', error);
    return NextResponse.json(
      { success: false, error: 'Failed to add subtitle' },
      { status: 500 }
    );
  }
}
